name: publish

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.vscode'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.vscode'
    
permissions:
  actions: write
  contents: write
  security-events: write

jobs:
  project:
    uses: heliannuuthus/integrate-deploy/.github/workflows/call-rust-tauri.yml@master
    permissions:
      contents: write
      packages: write
    with:
      rust_workdir: "src-tauri"
      node_workdir: "./"
