on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".vscode"

jobs:
  rust:
    uses: heliannuuthus/integrate-deploy/.github/workflows/call-rust.yml@v0.5.2
    with:
      workdir: "./src-tauri"
  node:
    uses: heliannuuthus/integrate-deploy/.github/workflows/call-node.yml@v0.5.2