on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".vscode"

jobs:
  rust:
    uses: heliannuuthus/integrate-deploy/.github/workflows/call-rust.yml@master
    with:
      workdir: "./src-tauri"
      toolchain: "nightly-2024-04-05"
  node:
    uses: heliannuuthus/integrate-deploy/.github/workflows/call-node.yml@master
